name: UserService CD

on:
  push:
    branches: 
      - development
      - master
      - feat/**
  pull_request:
    branches: [ master ]

jobs:

 push_to_docker_registry:
   # needs: build_and_test
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build lidl-twitter-user-service Image
      run: docker build . --file Dockerfile --tag yorgoc/userservice:v1
    - name: Push lidl-twitter-user-service Image
      run: docker push yorgoc/userservice:v1
